name: build-tests
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Install dependencies
        run: |
          curl -fLO https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-x86_64.zip
          unzip protoc-3.12.0-linux-x86_64.zip
          sudo mv bin/protoc /usr/local/bin/
          sudo mv include/* /usr/local/include/
          go get -u github.com/golang/protobuf/protoc-gen-go@v1.4.2
      - name: Generate
        run: go generate ./...
      - name: Test
        run: go test ./...
