name: build-tests
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: Install dependencies
        run: |
          curl -fLO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
          unzip protoc-3.15.8-linux-x86_64.zip
          sudo mv bin/protoc /usr/local/bin/
          sudo mv include/* /usr/local/include/
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
      - name: Generate
        run: go generate ./...
      - name: Test
        run: go test ./...
